<a href="https://colab.research.google.com/github/dayoungkimm/MS-AI-School/blob/main/Python_09_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###1. Numpty란?

C언어로 개발된 파이썬에서 과학적 계산을 위한 핵심 라이브러리.

다차원 배열 객체와 배열과 함게 작동하는 도구들을 제공한다.

하지만 고수준의 데이터 분석기능을 제공하지는 않기 때문에 Numpy 배열과 함께 Pandas와 같은 도구를 사용한다.

수학적 기능을 대부분 지원

In [1]:
import numpy as np          #numpy를 이제 줄여서 np로 부를거야

In [2]:
arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


###2. zeros, ones, empty로 배열 생성하기

1. zeros 

> 0으로 채워진 배열 만들기



In [3]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
car = np.zeros((3,3))
print(car)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


2. ones


> 1로 채워진 배열 만들기



In [5]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

3. empty


> 빈 배열 생성



In [6]:
np.empty((4,4))

array([[2.78827963e-316, 0.00000000e+000, 6.01334434e-154,
        1.14484088e+243],
       [2.42597833e+198, 9.77824555e+199, 6.01334653e-154,
        6.01347002e-154],
       [9.29787765e+199, 5.55603592e+180, 7.50009967e+247,
        9.82395831e+252],
       [1.46922886e+195, 1.27710827e-152, 6.52436916e+179,
        8.78422043e+247]])

###3. 특정 범위의 변수를 생성할 때 arange( )를 사용한다.

In [8]:
print(np.arange(10))
print(np.arange(1,10))
print(np.arange(1,10,2))

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


###4. ndarray 배열

In [9]:
#ndarray 배열의 모양, 차수, 데이터 타입 확인해보기
#꺾인 가로 [ ] 수에 따라 몇차원인지 확인가능 / 이건 2차원
#2차원인데 요소가 3개씩 있음 >> (2,3) 구조

arr = np.array([[1,2,3], [4,5,6]])  
print(arr)


[[1 2 3]
 [4 5 6]]


In [10]:
#차원 확인하기
arr.ndim

2

In [11]:
#데이터의 모양을 확인하는 방법
arr.shape

(2, 3)

In [13]:
# 데이터 타입의 확인
print(type(arr))
print(arr.dtype)      #배열 안의 데이터 타입 확인하기

<class 'numpy.ndarray'>
int64


In [14]:
# ndarray 배열의 타입 변환
arr_int = np.array([1,2,3,4])             #정수형 배열 생성
print(arr_int.dtype)
arr_float = arr_int.astype(np.float64)    #64bit 실수형으로 데이터 타입 변환하기
print(arr_float.dtype)

int64
float64


In [15]:
arr_str = np.array(['1', '2', '3', '4'])          #문자형(유니코드) 배열 생성
print(arr_str.dtype)

<U1


In [16]:
arr_int = arr_str.astype(np.int64)              #정수형으로 데이터 타입 변환하기
print(arr_int)
print(arr_int.dtype)

[1 2 3 4]
int64


###5. 배열의 연산 기능

In [17]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]


In [18]:
print(np.add(arr1,arr2))
print(np.multiply(arr1,arr2))

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]


###6. ndarray 배열 슬라이싱하기

In [19]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [20]:
arr_1 = arr[:2,1:3]       #[행,열] 슬라이싱
print(arr_1)

[[2 3]
 [5 6]]


###7. 원하는 요소에 접근하기

In [21]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr[0,2]

3

###8. 조건식 idx

In [22]:
arr = np.array([[1,2,3],[4,5,6]])
idx = arr > 3
print(idx)

[[False False False]
 [ True  True  True]]


In [23]:
arr[idx]      #true인 값만 추출

array([4, 5, 6])

###9. 예제

In [25]:
#텍스트 읽어들이기 (로딩하기)
np.loadtxt(fname='winequality-red.csv',delimiter = ';', skiprows =1)   #skip첫번째 행 속성(string)이므로

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [27]:
redwine = np.loadtxt(fname='winequality-red.csv',delimiter = ';', skiprows =1)

print(redwine)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


###10. 기초통계함수

sum 합계

mean 평균

std  표준 편차

var 분산 (std의 제곱)

min 최소값

max 최대값

In [28]:
print(redwine.sum())
print(redwine.sum(axis=0))        #0번축 기준으로 합계를 내기(->0 >> 세로축끼리의 합)
print(redwine.mean(axis=0))

152084.78194
[13303.1       843.985     433.29     4059.55      139.859   25384.
 74302.       1593.79794  5294.47     1052.38    16666.35     9012.     ]
[ 8.31963727  0.52782051  0.27097561  2.5388055   0.08746654 15.87492183
 46.46779237  0.99674668  3.3111132   0.65814884 10.42298311  5.63602251]


In [29]:
print(redwine.mean(axis=1))      #1번축 기준으로 평균내기 (밑으로 >> 가로축끼리의 평균)

[ 6.21198333 10.25456667  8.30825    ...  8.37347833  8.76795583
  7.7077075 ]


In [30]:
print(redwine[:,0].mean())               #0번축 기준으로 첫번째 칼럼 평균

8.31963727329581


In [31]:
print(redwine.max(axis=0))              #각 컬럼별 최대값
print(redwine.min(axis=0))              #각 컬럼별 최솟값

[ 15.9       1.58      1.       15.5       0.611    72.      289.
   1.00369   4.01      2.       14.9       8.     ]
[4.6     0.12    0.      0.9     0.012   1.      6.      0.99007 2.74
 0.33    8.4     3.     ]
